[package]
name = "comiconlinefree"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]
resolver = "2"

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs" }
wpcomics_template = { path = "../../template" }
